### ISSUE TITLE
Blank screen every time

### ISSUE THREAD

**Issue by roast247** [CommunityToolkit/Microsoft.Toolkit.Win32#338]
Why do I keep getting a blank screen? I literally installed the package to my visual studio project, put a website as source and when I run the program, its just blank. This seriously needs to be fixed. There is clearly a problem when half the people trying to use webview2 are saying they just come up with nothing but a blank screen. Can someone just fix it already? this is outrageous, Microsoft hypes up something that doesn't even work, losing my respect day by day. unreliable...

**Comment by michael-hawker** [comment]
@roast247 this is not the right GitHub for WebView2 feedback, as per our readme, please direct WebView2 feedback to https://github.com/MicrosoftEdge/WebViewFeedback

Please include more details about what your environment and configuration is, what type of project you're trying to create, and what code you're trying to run.
